# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
